name: Deploy ReactVite EduSpere Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: |
          docker build -t sathiskasasindu/edusphere-client \
          --build-arg REACT_APP_NODE_ENV='production' \
          --build-arg REACT_APP_SERVER_BASE_URL='http://13.60.31.119:4000' \
          .
        
      - name: Push Docker Image to Docker Hub
        run: docker push sathiskasasindu/edusphere-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Pull image from Docker Hub
        run: docker pull sathiskasasindu/edusphere-client:latest
        
      - name: Remove existing container if exists
        run: docker rm -f reactjseduspere-client-container || true
        
      - name: Run Docker Container
        run: |
          docker run -d -p 3001:80 \
          --name reactjseduspere-client-container \
          sathiskasasindu/edusphere-client:latest